import type { AuRegion } from "@prisma/client";
import type { TopicPack } from "./content";
import { PACKS as CORE_PACKS } from "./packs-core";

function makeTopics(
  categoryLabel: string,
  categoryLabelNp: string,
  stems: Array<{ en: string; np: string; angleEn: string; angleNp: string }>
): TopicPack["topics"] {
  return stems.map((stem) => ({
    title: stem.en,
    titleNp: stem.np,
    focusEn: [
      `${stem.angleEn} This Echo Manch development feature keeps the tone instructional for ${categoryLabel.toLowerCase()} desks.`,
      `Editors can test category landing pages while readers scan practical context about ${stem.en.toLowerCase()}.`,
      "Supporting sections outline timelines, stakeholder maps and questions reporters should ask before publishing.",
      "Background notes compare urban and rural angles without inventing official statistics.",
      "Safety, finance and emergency claims are intentionally avoided or kept generic in this demo dataset.",
      `A closing checklist helps QA teams confirm bilingual fields render correctly for ${categoryLabel} stories.`,
    ],
    focusNp: [
      `${stem.angleNp} इको माञ्चको यो विकास फिचर ${categoryLabelNp} डेस्कका लागि शिक्षामूलक स्वरमा राखिएको छ।`,
      `सम्पादकहरूले श्रेणी पृष्ठ परीक्षण गर्दा पाठकले ${stem.np} सम्बन्धी व्यावहारिक सन्दर्भ स्क्यान गर्न सक्छन्।`,
      "सहायक खण्डमा समयरेखा, सरोकारवाला नक्सा र प्रकाशनअघि सोध्नुपर्ने प्रश्न छन्।",
      "पृष्ठभूमिमा सहरी–ग्रामीण कोण तुलना छ तर आधिकारिक तथ्यांक बनाइएको छैन।",
      "सुरक्षा, वित्त र आपतकालीन दाबी डेमो डेटासेटमा सामान्य वा वर्जित राखिएको छ।",
      `${categoryLabelNp} कथाका द्विभाषी क्षेत्र सही देखिन्छन् कि भनी क्यूए चेकलिस्टले जाँच्न सहयोग गर्छ।`,
    ],
  }));
}

const EXTRA: TopicPack[] = [
  {
    categorySlug: "economy-business",
    imageQuery: "business office entrepreneurship",
    tagSlugs: ["business-tag", "markets", "feature"],
    topics: makeTopics("Business", "व्यापार", [
      {
        en: "Startup mentoring circles document pitch rehearsal habits",
        np: "स्टार्टअप मेन्टरिङ सर्कलमा पिच अभ्यास बानी दस्तावेजीकरण",
        angleEn: "Founders practise concise problem statements and customer discovery notes.",
        angleNp: "संस्थापकहरूले संक्षिप्त समस्या कथन र ग्राहक खोज नोट अभ्यास गर्छन्।",
      },
      {
        en: "Retail digitisation primers for neighbourhood shops",
        np: "छिमेकी पसलका लागि खुद्रा डिजिटलाइजेसन आधारपाठ",
        angleEn: "Inventory apps and QR payments are discussed as optional tools, not mandates.",
        angleNp: "इन्वेन्टरी एप र क्यूआर भुक्तानीलाई विकल्पका रूपमा मात्र छलफल गरिएको छ।",
      },
      {
        en: "Export paperwork literacy for first-time traders",
        np: "पहिलो पटक निर्यातकर्ताका लागि कागजी प्रक्रिया साक्षरता",
        angleEn: "Checklists cover invoices, packing lists and common terminology.",
        angleNp: "चेकलिस्टमा इनभ्वाइस, प्याकिङ सूची र सामान्य शब्दावली छन्।",
      },
      {
        en: "Women-led enterprises share bookkeeping workshop outlines",
        np: "महिला नेतृत्व उद्यमले बहीखाता कार्यशाला रूपरेखा बाँड्छन्",
        angleEn: "Training decks focus on cash logs and receipt hygiene.",
        angleNp: "तालिम सामग्री नगद लग र रसिद व्यवस्थापनमा केन्द्रित छ।",
      },
      {
        en: "Franchise FAQ templates for cautious entrepreneurs",
        np: "सतर्क उद्यमीका लागि फ्रान्चाइजी सामान्य प्रश्न टेम्प्लेट",
        angleEn: "Questions probe fees, territory rules and exit clauses without endorsing brands.",
        angleNp: "शुल्क, क्षेत्र नियम र बहिर्गमन दफाबारे प्रश्न छन्; कुनै ब्रान्ड सिफारिस छैन।",
      },
      {
        en: "Supply-chain delay explainers for editors on the business desk",
        np: "व्यापार डेस्क सम्पादकका लागि आपूर्ति श्रृंखला ढिलाइ व्याख्या",
        angleEn: "Language tips help avoid blaming single firms without evidence.",
        angleNp: "प्रमाणबिना एकल कम्पनीलाई दोष नदिने भाषा सुझाव दिइएको छ।",
      },
    ]),
  },
  {
    categorySlug: "technology-science",
    imageQuery: "technology computer AI software",
    tagSlugs: ["ai", "technology-tag", "digital-nepal", "software"],
    topics: makeTopics("Technology", "प्रविधि", [
      {
        en: "Municipal open-data portals: what citizens can actually download",
        np: "नगर खुला डेटा पोर्टल: नागरिकले वास्तवमा के डाउनलोड गर्न सक्छन्",
        angleEn: "A walkthrough separates machine-readable files from PDFs.",
        angleNp: "मेसिन-पढ्न मिल्ने फाइल र पीडीएफ छुट्याएर मार्गदर्शन छ।",
      },
      {
        en: "Newsroom AI assistive tools policy draft for editors",
        np: "सम्पादकका लागि समाचार कक्ष एआई सहायक उपकरण नीति मस्यौदा",
        angleEn: "Guidelines stress human review, disclosure and source checking.",
        angleNp: "मानवीय समीक्षा, खुलासा र स्रोत जाँचमा जोड दिइएको छ।",
      },
      {
        en: "Cyber hygiene basics for freelancers handling documents",
        np: "कागजात सम्हाल्ने फ्रीलान्सरका लागि साइबर स्वच्छता आधार",
        angleEn: "Password managers, 2FA and phishing examples stay generic.",
        angleNp: "पासवर्ड व्यवस्थापक, दुई चरण प्रमाणीकरण र फिसिङ उदाहरण सामान्य छन्।",
      },
      {
        en: "5G coverage maps literacy for consumer reporters",
        np: "उपभोक्ता रिपोर्टरका लागि ५जी कभरेज नक्सा साक्षरता",
        angleEn: "Readers learn why signal heatmaps need ground-truth caveats.",
        angleNp: "सिग्नल हिटम्यापलाई स्थलगत सत्यसँग मिलाउनुपर्ने कुरा बताइएको छ।",
      },
      {
        en: "Digital public services UX notes from helpdesk shadows",
        np: "हेल्पडेस्क अवलोकनबाट डिजिटल सार्वजनिक सेवा यूएक्स नोट",
        angleEn: "Common friction points include OTP delays and form validation errors.",
        angleNp: "ओटीपी ढिलाइ र फारम त्रुटि जस्ता सामान्य झन्झट उल्लेख छन्।",
      },
      {
        en: "Open-source localisation projects for Nepali interfaces",
        np: "नेपाली इन्टरफेसका लागि खुला स्रोत स्थानीयकरण आयोजना",
        angleEn: "Contributors discuss glossary consistency and font rendering.",
        angleNp: "योगदानकर्ताले शब्दकोश एकरूपता र फन्ट रेन्डरिङ छलफल गर्छन्।",
      },
    ]),
  },
  {
    categorySlug: "sports",
    imageQuery: "sports cricket football stadium",
    tagSlugs: ["cricket", "football", "feature"],
    topics: makeTopics("Sports", "खेलकुद", [
      {
        en: "Community cricket nets: scheduling and safety checklists",
        np: "सामुदायिक क्रिकेट नेट: तालिका र सुरक्षा चेकलिस्ट",
        angleEn: "Clubs share warm-up routines and equipment inspection habits.",
        angleNp: "क्लबले वार्म-अप र उपकरण जाँच बानी बाँड्छन्।",
      },
      {
        en: "School football festivals emphasise fair play messaging",
        np: "विद्यालय फुटबल महोत्सवमा निष्पक्ष खेल सन्देश",
        angleEn: "Coaches focus on hydration, respect and sideline behaviour.",
        angleNp: "कोचले जलयोजन, सम्मान र साइडलाइन व्यवहारमा जोड दिन्छन्।",
      },
      {
        en: "Women athletes’ pathway explainers for local federations",
        np: "स्थानीय महासंघका लागि महिला खेलाडी मार्ग व्याख्या",
        angleEn: "Training calendars and scholarship FAQ templates are outlined.",
        angleNp: "तालिम पात्रो र छात्रवृत्ति सामान्य प्रश्न रूपरेखा दिइएको छ।",
      },
      {
        en: "Stadium accessibility audits for family match days",
        np: "पारिवारिक खेल दिनका लागि स्टेडियम पहुँच अडिट",
        angleEn: "Ramps, seating and medical posts appear as planning prompts.",
        angleNp: "र्‍याम्प, सिट र मेडिकल पोस्ट योजना संकेतका रूपमा छन्।",
      },
      {
        en: "Sports physiotherapy primers for weekend runners",
        np: "सप्ताहन्त धावकका लागि खेलफिजियोथेरापी आधार",
        angleEn: "Recovery guidance stays non-clinical and general.",
        angleNp: "रिकभरी मार्गदर्शन गैर-क्लिनिकल र सामान्य छ।",
      },
      {
        en: "Esports club codes of conduct for campus tournaments",
        np: "क्याम्पस प्रतियोगिताका लागि इस्पोर्ट्स क्लब आचारसंहिता",
        angleEn: "Moderation, streaming consent and anti-harassment rules are summarised.",
        angleNp: "मोडरेशन, स्ट्रिमिङ सहमति र उत्पीडन विरोधी नियम सारांश छन्।",
      },
    ]),
  },
  {
    categorySlug: "entertainment",
    imageQuery: "entertainment film music concert",
    tagSlugs: ["film", "music", "feature"],
    topics: makeTopics("Entertainment", "मनोरञ्जन", [
      {
        en: "Independent film festival volunteer handbooks",
        np: "स्वतन्त्र चलचित्र महोत्सव स्वयंसेवक हातेपुस्तिका",
        angleEn: "Roles cover ushering, subtitle checks and guest care.",
        angleNp: "भूमिकामा दर्शक सहयोग, उपशीर्षक जाँच र पाहुना सेवा छन्।",
      },
      {
        en: "Folk music archiving workshops for community radio",
        np: "सामुदायिक रेडियोका लागि लोक संगीत अभिलेख कार्यशाला",
        angleEn: "Consent forms and metadata fields are emphasised.",
        angleNp: "सहमति फारम र मेटाडेटा क्षेत्रमा जोड दिइएको छ।",
      },
      {
        en: "Theatre lighting safety primers for school productions",
        np: "विद्यालय नाटकका लागि थिएटर प्रकाश सुरक्षा आधार",
        angleEn: "Cable management and fire exits headline the checklist.",
        angleNp: "केबल व्यवस्थापन र आगो निस्कने बाटो चेकलिस्टमा छन्।",
      },
      {
        en: "Podcast editing ethics for interview shows",
        np: "अन्तर्वार्ता शोका लागि पोडकास्ट सम्पादन नैतिकता",
        angleEn: "Hosts discuss cuts, context and correction notes.",
        angleNp: "होस्टले कट, सन्दर्भ र सच्याउने नोट छलफल गर्छन्।",
      },
      {
        en: "Streaming subtitle quality notes for bilingual releases",
        np: "द्विभाषी रिलिजका लागि स्ट्रिमिङ उपशीर्षक गुणस्तर नोट",
        angleEn: "Timing, honorifics and song lyric policies are reviewed.",
        angleNp: "समय मिलान, आदरार्थी र गीत शब्द नीति समीक्षा छ।",
      },
      {
        en: "Cultural calendar planning for municipal stages",
        np: "नगर मञ्चका लागि सांस्कृतिक पात्रो योजना",
        angleEn: "Booking buffers and weather contingencies appear as soft tips.",
        angleNp: "बुकिङ बफर र मौसम वैकल्पिक योजना नरम सुझावका रूपमा छन्।",
      },
    ]),
  },
  {
    categorySlug: "health-lifestyle",
    imageQuery: "health hospital healthcare doctor",
    tagSlugs: ["public-health", "hospitals", "explainer"],
    topics: makeTopics("Health", "स्वास्थ्य", [
      {
        en: "Primary care triage posters rewritten in plain language",
        np: "सामान्य भाषामा पुनर्लेखित प्राथमिक हेरचाह ट्रायज पोस्टर",
        angleEn: "Clinics test whether symbols reduce waiting-room confusion.",
        angleNp: "प्रतीकले प्रतीक्षालय भ्रम घटाउँछ कि भनी क्लिनिक परीक्षण गर्छन्।",
      },
      {
        en: "Mental health helpline directory literacy for desks",
        np: "डेस्कका लागि मानसिक स्वास्थ्य हेल्पलाइन निर्देशिका साक्षरता",
        angleEn: "Reporters learn to verify hours and languages without publishing medical advice.",
        angleNp: "मेडिकल सल्लाह नदिई समय र भाषा पुष्टि गर्ने अभ्यास छ।",
      },
      {
        en: "Vaccination cold-chain explainers for community reporters",
        np: "सामुदायिक रिपोर्टरका लागि खोप कोल्ड-चेन व्याख्या",
        angleEn: "Temperature logging concepts stay high level and non-alarmist.",
        angleNp: "तापमान लग अवधारणा उच्च स्तरमा र गैर-आतंककारी छ।",
      },
      {
        en: "Hospital wayfinding redesign case notes",
        np: "अस्पताल बाटो देखाउने डिजाइन पुनरावलोकन नोट",
        angleEn: "Colour coding and multilingual signs are discussed as UX patterns.",
        angleNp: "रङ कोड र बहुभाषी संकेत यूएक्स ढाँचाका रूपमा छन्।",
      },
      {
        en: "Nutrition label reading workshops for families",
        np: "परिवारका लागि पोषण लेबल पढ्ने कार्यशाला",
        angleEn: "Sugar, salt and portion cues are illustrated without brand attacks.",
        angleNp: "चिनी, नुन र पोर्सन संकेत ब्रान्ड आक्रमणबिना देखाइएको छ।",
      },
      {
        en: "Monsoon hygiene reminders packaged as service journalism",
        np: "मनसुन स्वच्छता स्मरण सेवा पत्रकारिताका रूपमा",
        angleEn: "Water storage and mosquito tips remain evergreen.",
        angleNp: "पानी भण्डारण र लामखुट्टे सुझाव सधैं उपयोगी रहन्छन्।",
      },
    ]),
  },
  {
    categorySlug: "education",
    imageQuery: "education students university school",
    tagSlugs: ["education-tag", "students", "feature"],
    topics: makeTopics("Education", "शिक्षा", [
      {
        en: "Scholarship essay clinics without paid-service pitches",
        np: "सशुल्क सेवा प्रचारबिना छात्रवृत्ति निबन्ध क्लिनिक",
        angleEn: "Mentors focus on structure, evidence and honest voice.",
        angleNp: "मेन्टरले संरचना, प्रमाण र इमानदार स्वरमा जोड दिन्छन्।",
      },
      {
        en: "Library makerspace rules for secondary schools",
        np: "माध्यामिक विद्यालयका लागि लाइब्रेरी मेकर्स्पेस नियम",
        angleEn: "Tool safety and booking slots headline the handbook.",
        angleNp: "औजार सुरक्षा र बुकिङ स्लट हातेपुस्तिकामा छन्।",
      },
      {
        en: "Parent-teacher conference conversation cards",
        np: "अभिभावक–शिक्षक बैठक कुराकानी कार्ड",
        angleEn: "Prompts encourage listening before problem-solving.",
        angleNp: "समस्या समाधानअघि सुन्ने अभ्यास प्रोत्साहित गरिएको छ।",
      },
      {
        en: "Open educational resources cataloguing tips",
        np: "खुला शैक्षिक स्रोत सूचीकरण सुझाव",
        angleEn: "Licences, attribution and offline mirroring are covered.",
        angleNp: "लाइसेन्स, श्रेय र अफलाइन मिरर समेटिएको छ।",
      },
      {
        en: "Exam stress workshops framed as wellbeing support",
        np: "कल्याण सहयोगका रूपमा परीक्षा तनाव कार्यशाला",
        angleEn: "Sleep, breaks and peer support stay non-clinical.",
        angleNp: "निद्रा, ब्रेक र साथी सहयोग गैर-क्लिनिकल छन्।",
      },
      {
        en: "Campus journalism starter kits for college papers",
        np: "कलेज पत्रिकाका लागि क्याम्पस पत्रकारिता स्टार्टर किट",
        angleEn: "Ethics, corrections and photo consent form templates included.",
        angleNp: "नैतिकता, सच्याइ र फोटो सहमति फारम टेम्प्लेट छन्।",
      },
    ]),
  },
  {
    categorySlug: "society",
    imageQuery: "society community people civic",
    tagSlugs: ["society-tag", "feature", "explainer"],
    topics: makeTopics("Society", "समाज", [
      {
        en: "Neighbourhood clean-up coordination playbooks",
        np: "छिमेक सरसफाइ समन्वय प्लेबुक",
        angleEn: "Waste sorting stations and volunteer shifts are mapped.",
        angleNp: "फोहोर छुट्याउने स्टेसन र स्वयंसेवक सिफ्ट नक्सा छन्।",
      },
      {
        en: "Disability inclusion checklists for public events",
        np: "सार्वजनिक कार्यक्रमका लागि अपाङ्गता समावेशी चेकलिस्ट",
        angleEn: "Access routes, seating and communication aids are listed.",
        angleNp: "पहुँच मार्ग, सिट र सञ्चार सहयोग सूचीकृत छन्।",
      },
      {
        en: "Community mediation FAQ for minor disputes",
        np: "सानो विवादका लागि सामुदायिक मध्यस्थता सामान्य प्रश्न",
        angleEn: "Tone remains non-legal and referral-oriented.",
        angleNp: "स्वर गैर-कानुनी र सिफारिसमुखी छ।",
      },
      {
        en: "Senior citizen digital banking escort programmes",
        np: "ज्येष्ठ नागरिक डिजिटल बैंकिङ साथी कार्यक्रम",
        angleEn: "Volunteers practise patience scripts and fraud red flags.",
        angleNp: "स्वयंसेवकले धैर्य संवाद र ठगी संकेत अभ्यास गर्छन्।",
      },
      {
        en: "Mutual aid pantry inventory sheets for winter",
        np: "हिउँदका लागि पारस्परिक सहायता प्यान्ट्री मौज्दात पाना",
        angleEn: "Donation intake and expiry tracking are emphasised.",
        angleNp: "दान प्राप्ति र म्याद ट्र्याकिङमा जोड छ।",
      },
      {
        en: "Public transport etiquette campaigns for peak hours",
        np: "पीक आवरका लागि सार्वजनिक यातायात शिष्टाचार अभियान",
        angleEn: "Priority seating reminders stay friendly, not punitive.",
        angleNp: "प्राथमिकता सिट स्मरण मैत्रीपूर्ण छ, दण्डात्मक होइन।",
      },
    ]),
  },
  {
    categorySlug: "world",
    imageQuery: "world international global diplomacy",
    tagSlugs: ["international-tag", "explainer"],
    topics: makeTopics("World", "विश्व", [
      {
        en: "How to read multilateral summit communiqués",
        np: "बहुपक्षीय शिखर सम्मेलन विज्ञप्ति कसरी पढ्ने",
        angleEn: "Reporters scan verbs that signal intent versus commitment.",
        angleNp: "इरादा र प्रतिबद्धता छुट्याउने क्रिया खोजिन्छ।",
      },
      {
        en: "Diaspora media desks: sourcing without rumour cascades",
        np: "डायस्पोरा मिडिया डेस्क: अफवाह श्रृंखलाबिना स्रोत",
        angleEn: "Verification ladders and time-zone coordination tips included.",
        angleNp: "पुष्टि सिँढी र समय क्षेत्र समन्वय सुझाव छन्।",
      },
      {
        en: "Climate COP side-event coverage templates",
        np: "जलवायु सीओपी साइड-इभेन्ट कभरेज टेम्प्लेट",
        angleEn: "Panels, pavilions and protest logistics are separated clearly.",
        angleNp: "प्यानल, प्याभिलियन र प्रदर्शन व्यवस्था छुट्याइएको छ।",
      },
      {
        en: "Global supply shock explainers for general audiences",
        np: "सामान्य पाठकका लागि विश्व आपूर्ति झट्का व्याख्या",
        angleEn: "Shipping, ports and last-mile metaphors stay accessible.",
        angleNp: "ढुवानी, बन्दरगाह र अन्तिम माइल रूपक सजिलो भाषामा छन्।",
      },
      {
        en: "Humanitarian appeal language guides for desks",
        np: "डेस्कका लागि मानवीय अपील भाषा गाइड",
        angleEn: "Dignity-first phrasing and donation verification reminders.",
        angleNp: "मर्यादा प्राथमिक भाषा र दान पुष्टि स्मरण छन्।",
      },
      {
        en: "Cross-border student exchange orientation notes",
        np: "सीमापार विद्यार्थी आदानप्रदान अभिमुखीकरण नोट",
        angleEn: "Visa timelines discussed as ranges, not guarantees.",
        angleNp: "भिसा समयरेखा ग्यारेन्टी होइन दायराका रूपमा छन्।",
      },
    ]),
  },
  {
    categorySlug: "health-lifestyle",
    imageQuery: "lifestyle wellness food culture",
    tagSlugs: ["lifestyle-tag", "feature"],
    topics: makeTopics("Lifestyle", "जीवनशैली", [
      {
        en: "Weekend city walking routes with heritage stops",
        np: "सप्ताहन्त सहरी पैदल मार्ग र सम्पदा स्टप",
        angleEn: "Maps favour public plazas and museums over private venues.",
        angleNp: "निजी स्थलभन्दा सार्वजनिक चोक र संग्रहालय प्राथमिकता छ।",
      },
      {
        en: "Home cooking batch-prep guides for busy households",
        np: "व्यस्त घरपरिवारका लागि होम कुकिङ ब्याच-तयारी गाइड",
        angleEn: "Recipes stay flexible and cuisine-agnostic.",
        angleNp: "रेसिपी लचिलो र कुनै एक व्यञ्जनमा सीमित छैनन्।",
      },
      {
        en: "Indoor plant care calendars for apartments",
        np: "अपार्टमेन्टका लागि इनडोर बिरुवा हेरचाह पात्रो",
        angleEn: "Light and watering cues avoid product placements.",
        angleNp: "उज्यालो र पानी संकेतमा उत्पादन प्रचार छैन।",
      },
      {
        en: "Digital declutter routines for phone photo libraries",
        np: "फोन फोटो लाइब्रेरी डिजिटल सफाइ दिनचर्या",
        angleEn: "Backup-before-delete steps are underlined.",
        angleNp: "मेटाउनुअघि ब्याकअप चरण जोड दिइएको छ।",
      },
      {
        en: "Community yoga etiquette cards for parks",
        np: "पार्कका लागि सामुदायिक योग शिष्टाचार कार्ड",
        angleEn: "Space sharing and volume tips keep the tone light.",
        angleNp: "ठाउँ बाँडफाँड र आवाज सुझाव हल्का स्वरमा छन्।",
      },
      {
        en: "Thrift and repair café conversation starters",
        np: "थ्रिफ्ट र मर्मत क्याफे कुराकानी सुरुवात",
        angleEn: "Sustainability framing stays practical, not preachy.",
        angleNp: "दिगोपना व्यावहारिक छ, उपदेशात्मक होइन।",
      },
    ]),
  },
  {
    categorySlug: "tourism-agriculture",
    imageQuery: "tourism mountains trekking nepal travel",
    tagSlugs: ["tourism", "trekking", "feature"],
    topics: makeTopics("Tourism", "पर्यटन", [
      {
        en: "Teahouse etiquette primers for first-time trekkers",
        np: "पहिलो पटक ट्रेकरका लागि चियाघर शिष्टाचार आधार",
        angleEn: "Boot cleaning, quiet hours and waste packing are covered.",
        angleNp: "जुत्ता सफाइ, शान्त समय र फोहोर बोक्ने अभ्यास समेटिएको छ।",
      },
      {
        en: "Homestay host checklists for cultural hospitality",
        np: "सांस्कृतिक आतिथ्यका लागि होमस्टे होस्ट चेकलिस्ट",
        angleEn: "Consent for photos and meal preferences are emphasised.",
        angleNp: "फोटो सहमति र खाना प्राथमिकतामा जोड छ।",
      },
      {
        en: "Monsoon travel contingency cards for road corridors",
        np: "सडक करिडोरका लागि मनसुन यात्रा वैकल्पिक कार्ड",
        angleEn: "Delay language stays cautious without inventing closures.",
        angleNp: "बन्द बाटो नबनाई सावधान ढिलाइ भाषा प्रयोग छ।",
      },
      {
        en: "City museum pass planning for family itineraries",
        np: "पारिवारिक यात्राका लागि सहर संग्रहालय पास योजना",
        angleEn: "Ticketing windows and accessibility notes are summarised.",
        angleNp: "टिकट काउन्टर र पहुँच नोट सारांश छन्।",
      },
      {
        en: "Photography ethics near sacred sites",
        np: "पवित्र स्थल नजिक फोटोग्राफी नैतिकता",
        angleEn: "Drone and flash restrictions are presented as reminders.",
        angleNp: "ड्रोन र फ्ल्यास प्रतिबन्ध स्मरणका रूपमा छन्।",
      },
      {
        en: "Off-season hospitality staffing rotation ideas",
        np: "अफ-सिजन आतिथ्य जनशक्ति रोटेसन विचार",
        angleEn: "Training cross-skills helps retain local workers.",
        angleNp: "क्रस-स्किल तालिमले स्थानीय कामदार टिकाइराख्न सहयोग गर्छ।",
      },
    ]),
  },
  {
    categorySlug: "tourism-agriculture",
    imageQuery: "agriculture farming crops farmers",
    tagSlugs: ["agriculture-tag", "farmers", "feature"],
    topics: makeTopics("Agriculture", "कृषि", [
      {
        en: "Seed storage literacy for cooperative warehouses",
        np: "सहकारी गोदामका लागि बीउ भण्डारण साक्षरता",
        angleEn: "Moisture and labelling routines stay instructional.",
        angleNp: "आर्द्रता र लेबल दिनचर्या शिक्षामूलक छन्।",
      },
      {
        en: "Market day pricing boards redesigned for clarity",
        np: "स्पष्टताका लागि बजार दिन मूल्य बोर्ड पुनः डिजाइन",
        angleEn: "Units and time stamps reduce buyer confusion.",
        angleNp: "एकाइ र समय छापले खरीददार भ्रम घटाउँछ।",
      },
      {
        en: "Soil testing appointment workflows for extension desks",
        np: "विस्तार डेस्कका लागि माटो परीक्षण अपोइन्टमेन्ट कार्यप्रवाह",
        angleEn: "Sample bagging steps are listed without lab brand names.",
        angleNp: "नमूना झोला चरण ल्याब ब्रान्डबिना सूचीकृत छन्।",
      },
      {
        en: "Irrigation roster transparency for shared canals",
        np: "साझा नहरका लागि सिँचाइ तालिका पारदर्शिता",
        angleEn: "Conflict-prevention tips favour dialogue over blame.",
        angleNp: "द्वन्द्व रोकथाम सुझाव दोषभन्दा संवादमा केन्द्रित छन्।",
      },
      {
        en: "Post-harvest handling cards for perishable crops",
        np: "नाशिने बालीका लागि फसलपछि ह्यान्डलिङ कार्ड",
        angleEn: "Shade, crates and transport timing cues included.",
        angleNp: "छायाँ, क्रेट र ढुवानी समय संकेत छन्।",
      },
      {
        en: "Youth agripreneur mentorship session outlines",
        np: "युवा कृषि उद्यमी मेन्टरसिप सत्र रूपरेखा",
        angleEn: "Business canvas prompts stay sector-agnostic.",
        angleNp: "व्यवसाय क्यानभास संकेत क्षेत्र-तटस्थ छन्।",
      },
    ]),
  },
  {
    categorySlug: "technology-science",
    imageQuery: "science research laboratory discovery",
    tagSlugs: ["science-tag", "research", "explainer"],
    topics: makeTopics("Science", "विज्ञान", [
      {
        en: "Citizen science bird counts for weekend volunteers",
        np: "सप्ताहन्त स्वयंसेवकका लागि नागरिक विज्ञान चरा गणना",
        angleEn: "Observation apps and ethics around nesting sites are noted.",
        angleNp: "अवलोकन एप र गुँड स्थल नैतिकता उल्लेख छ।",
      },
      {
        en: "Lab open-day scripts for school visits",
        np: "विद्यालय भ्रमणका लागि ल्याब खुला दिन स्क्रिप्ट",
        angleEn: "Safety goggles and no-touch rules headline the brief.",
        angleNp: "सेफ्टी चस्मा र नछुने नियम ब्रिफमा छन्।",
      },
      {
        en: "Astronomy night checklists for clubs",
        np: "क्लबका लागि खगोल रात्रि चेकलिस्ट",
        angleEn: "Light pollution and weather contingency tips included.",
        angleNp: "प्रकाश प्रदूषण र मौसम वैकल्पिक सुझाव छन्।",
      },
      {
        en: "Science communication pitfalls: correlation vs causation",
        np: "विज्ञान सञ्चार कमजोरी: सहसम्बन्ध बनाम कारण",
        angleEn: "Headline hygiene examples help editors avoid hype.",
        angleNp: "हेडलाइन स्वच्छता उदाहरणले हाइप रोक्न सहयोग गर्छ।",
      },
      {
        en: "Museum specimen labelling workshops",
        np: "संग्रहालय नमूना लेबल कार्यशाला",
        angleEn: "Accession numbers and provenance fields are practised.",
        angleNp: "एक्सेसन नम्बर र उत्पत्ति क्षेत्र अभ्यास गरिन्छ।",
      },
      {
        en: "Open research preprint reading guides for desks",
        np: "डेस्कका लागि खुला अनुसन्धान प्रिप्रिन्ट पढाइ गाइड",
        angleEn: "Versioning and peer-review status cues are explained.",
        angleNp: "संस्करण र पीयर-रिभ्यू स्थिति संकेत व्याख्या छ।",
      },
    ]),
  },
  {
    categorySlug: "society",
    imageQuery: "environment climate forest nature",
    tagSlugs: ["climate", "environment-tag", "explainer"],
    topics: makeTopics("Environment", "वातावरण", [
      {
        en: "Urban tree inventory methods for ward volunteers",
        np: "वडा स्वयंसेवकका लागि सहरी रूख सूची विधि",
        angleEn: "Species ID and watering notes stay community-friendly.",
        angleNp: "प्रजाति पहिचान र पानी नोट समुदायमैत्री छन्।",
      },
      {
        en: "Plastic reduction challenge trackers for schools",
        np: "विद्यालयका लागि प्लास्टिक घटाउने चुनौती ट्र्याकर",
        angleEn: "Measurement is approximate and educational, not punitive.",
        angleNp: "मापन अनुमानित र शैक्षिक छ, दण्डात्मक होइन।",
      },
      {
        en: "Riverbank clean-up safety briefings",
        np: "नदी किनार सरसफाइ सुरक्षा ब्रिफिङ",
        angleEn: "Footwear, gloves and hydration cues are listed.",
        angleNp: "जुत्ता, पञ्जा र जलयोजन संकेत सूचीकृत छन्।",
      },
      {
        en: "Air quality index reading guides for families",
        np: "परिवारका लागि वायु गुणस्तर सूचकांक पढाइ गाइड",
        angleEn: "Colour scales are explained without medical prescriptions.",
        angleNp: "रङ स्केल मेडिकल प्रिस्क्रिप्शनबिना व्याख्या छ।",
      },
      {
        en: "Community solar FAQ for housing committees",
        np: "आवास समितिका लागि सामुदायिक सौर्य सामान्य प्रश्न",
        angleEn: "Maintenance ownership questions are emphasised.",
        angleNp: "मर्मत स्वामित्व प्रश्नमा जोड दिइएको छ।",
      },
      {
        en: "Wildlife corridor signage literacy for drivers",
        np: "चालकका लागि वन्यजन्तु करिडोर संकेत साक्षरता",
        angleEn: "Speed and night driving reminders stay general.",
        angleNp: "गति र रात्रि ड्राइभिङ स्मरण सामान्य छन्।",
      },
    ]),
  },
  {
    categorySlug: "national",
    imageQuery: "nepal national civic infrastructure",
    tagSlugs: ["national-tag", "feature"],
    topics: makeTopics("National", "राष्ट्रिय", [
      {
        en: "Inter-province bus passenger rights explainers",
        np: "अन्तर-प्रदेश बस यात्रु अधिकार व्याख्या",
        angleEn: "Ticket, baggage and complaint pathway notes for travellers.",
        angleNp: "यात्रुका लागि टिकट, सामान र उजुरी मार्ग नोट।",
      },
      {
        en: "National ID document renewal appointment tips",
        np: "राष्ट्रिय परिचयपत्र नवीकरण अपोइन्टमेन्ट सुझाव",
        angleEn: "Checklists avoid promising processing times.",
        angleNp: "प्रशोधन समय वाचा नगरी चेकलिस्ट दिइएको छ।",
      },
      {
        en: "Public holiday calendar planning for newsrooms",
        np: "समाचार कक्षका लागि सार्वजनिक बिदा पात्रो योजना",
        angleEn: "Staffing and evergreen package ideas included.",
        angleNp: "स्टाफिङ र सधैंहरियो प्याकेज विचार छन्।",
      },
      {
        en: "Disaster drill communication templates for districts",
        np: "जिल्लाका लागि विपद् अभ्यास सञ्चार टेम्प्लेट",
        angleEn: "Siren tests and shelter signs are described carefully.",
        angleNp: "साइरन परीक्षण र आश्रय संकेत सावधानीपूर्वक वर्णन छ।",
      },
      {
        en: "Language access in national helplines",
        np: "राष्ट्रिय हेल्पलाइनमा भाषा पहुँच",
        angleEn: "Routing and callback expectations stay realistic.",
        angleNp: "रुटिङ र कलब्याक अपेक्षा यथार्थपरक छन्।",
      },
      {
        en: "Infrastructure photo caption standards for desks",
        np: "डेस्कका लागि पूर्वाधार फोटो क्याप्शन मापदण्ड",
        angleEn: "Location accuracy and worker privacy reminders.",
        angleNp: "स्थान शुद्धता र कामदार गोपनीयता स्मरण।",
      },
    ]),
  },
  {
    categorySlug: "world",
    imageQuery: "international diplomacy global affairs",
    tagSlugs: ["international-tag", "explainer"],
    topics: makeTopics("International", "अन्तर्राष्ट्रिय", [
      {
        en: "Embassy consular hours literacy for travellers",
        np: "यात्रुका लागि दूतावास कन्सुलर समय साक्षरता",
        angleEn: "Appointment systems and emergency contacts summarised.",
        angleNp: "अपोइन्टमेन्ट प्रणाली र आपतकालीन सम्पर्क सारांश।",
      },
      {
        en: "Trade fair reporting kits for first-time correspondents",
        np: "पहिलो पटक संवाददाताका लागि व्यापार मेला रिपोर्टिङ किट",
        angleEn: "Booth etiquette and claim verification tips included.",
        angleNp: "बुथ शिष्टाचार र दाबी पुष्टि सुझाव छन्।",
      },
      {
        en: "Sports mega-event media accreditation primers",
        np: "खेल महाइभेन्ट मिडिया प्रत्यायन आधार",
        angleEn: "Badge zones and filing centre logistics explained.",
        angleNp: "ब्याज जोन र फाइलिङ सेन्टर व्यवस्था व्याख्या।",
      },
      {
        en: "Cultural exchange exhibition caption writing tips",
        np: "सांस्कृतिक आदानप्रदान प्रदर्शनी क्याप्शन लेखन सुझाव",
        angleEn: "Respectful naming and loan object credits emphasised.",
        angleNp: "आदरपूर्ण नामकरण र उधारो वस्तु श्रेयमा जोड।",
      },
      {
        en: "Remote correspondent security checklists",
        np: "रिमोट संवाददाता सुरक्षा चेकलिस्ट",
        angleEn: "Check-ins and equipment insurance prompts stay high level.",
        angleNp: "चेक-इन र उपकरण बीमा संकेत उच्च स्तरमा छन्।",
      },
      {
        en: "Treaty explainer formats for general audiences",
        np: "सामान्य पाठकका लागि सन्धि व्याख्या ढाँचा",
        angleEn: "Parties, scope and timelines without legal overclaim.",
        angleNp: "पक्ष, दायरा र समयरेखा कानुनी अति दाबीबिना।",
      },
    ]),
  },
  {
    categorySlug: "opinion",
    imageQuery: "opinion editorial analysis newspaper",
    tagSlugs: ["explainer", "feature"],
    topics: makeTopics("Opinion", "विचार", [
      {
        en: "Why service journalism still needs strong editors",
        np: "सेवा पत्रकारितालाई किन बलियो सम्पादक चाहिन्छ",
        angleEn: "An essay argues for clarity over virality in public-interest beats.",
        angleNp: "सार्वजनिक सरोकार बीटमा भाइरलताभन्दा स्पष्टतामा जोड दिने निबन्ध।",
      },
      {
        en: "Bilingual newsrooms and the craft of parallel storytelling",
        np: "द्विभाषी समाचार कक्ष र समानान्तर कथाशिल्प",
        angleEn: "Writers reflect on adapting tone rather than literal translation.",
        angleNp: "शब्दशः अनुवादभन्दा स्वर अनुकूलनमा लेखकको चिन्तन।",
      },
      {
        en: "Corrections culture as a trust strategy",
        np: "विश्वास रणनीतिका रूपमा सच्याउने संस्कृति",
        angleEn: "Transparent fixes beat silent edits, the column argues.",
        angleNp: "मौन सम्पादनभन्दा पारदर्शी सुधार राम्रो भन्ने तर्क।",
      },
      {
        en: "Audience metrics without losing editorial judgement",
        np: "सम्पादकीय विवेक नगुमाई दर्शक मेट्रिक्स",
        angleEn: "Dashboards inform, they should not dictate every headline.",
        angleNp: "ड्यासबोर्ड जानकारी दिन्छन्, हरेक हेडलाइन निर्धारण गर्नु हुँदैन।",
      },
      {
        en: "Community notes from readers who fact-check kindly",
        np: "नम्रतापूर्वक तथ्य जाँच्ने पाठकका समुदाय नोट",
        angleEn: "Civility norms for tip lines and email replies.",
        angleNp: "टिप लाइन र इमेल जवाफका शिष्टता मापदण्ड।",
      },
      {
        en: "On labelling explainers, features and news clearly",
        np: "व्याख्या, फिचर र समाचार स्पष्ट लेबल गर्नेबारे",
        angleEn: "Format honesty helps audiences set expectations.",
        angleNp: "ढाँचा इमानदारिताले पाठक अपेक्षा मिलाउँछ।",
      },
    ]),
  },
];

export type AustraliaTopic = {
  categorySlug: string;
  auRegion: AuRegion;
  title: string;
  titleNp: string;
  imageQuery: string;
  tagSlugs: string[];
  focusEn: string[];
  focusNp: string[];
  placeEn: string;
  placeNp: string;
};

export const AUSTRALIA_TOPICS: AustraliaTopic[] = [
  {
    categorySlug: "world",
    auRegion: "NSW",
    title: "Sydney Nepali community centres expand weekend language classes",
    titleNp: "सिड्नी नेपाली सामुदायिक केन्द्रमा सप्ताहन्त भाषा कक्षा विस्तार",
    imageQuery: "sydney australia city",
    tagSlugs: ["australia", "sydney", "nepali-community", "education-tag"],
    placeEn: "Sydney",
    placeNp: "सिड्नी",
    focusEn: [
      "Volunteer teachers outline enrolment habits and classroom resources for diaspora families.",
      "Centres emphasise cultural festivals alongside literacy support.",
      "Demo coverage avoids inventing council grant figures.",
      "Parents share general tips on balancing school and weekend programmes.",
      "Editors can link related education explainers from Nepal desks.",
      "The feature ends with a directory literacy checklist for newcomers.",
    ],
    focusNp: [
      "स्वयंसेवक शिक्षकले डायस्पोरा परिवारका लागि भर्ना बानी र कक्षा स्रोत बताउँछन्।",
      "केन्द्रले साक्षरतासँगै सांस्कृतिक महोत्सवमा जोड दिन्छन्।",
      "डेमो कभरेजले परिषद् अनुदान अंक बनाउँदैन।",
      "अभिभावकले विद्यालय र सप्ताहन्त कार्यक्रम सन्तुलनका सामान्य सुझाव बाँड्छन्।",
      "सम्पादकले नेपाल डेस्कका शिक्षा व्याख्या जोड्न सक्छन्।",
      "नयाँ आउनेका लागि निर्देशिका साक्षरता चेकलिस्टसहित फिचर सकिन्छ।",
    ],
  },
  {
    categorySlug: "education",
    auRegion: "VIC",
    title: "Melbourne universities host orientation modules for South Asian students",
    titleNp: "मेलबर्न विश्वविद्यालयमा दक्षिण एसियाली विद्यार्थी अभिमुखीकरण मोड्युल",
    imageQuery: "melbourne australia university",
    tagSlugs: ["australia", "melbourne", "students", "education-tag"],
    placeEn: "Melbourne",
    placeNp: "मेलबर्न",
    focusEn: [
      "Orientation topics include housing scams awareness and campus wellbeing services.",
      "Student unions discuss peer mentoring without publishing private cases.",
      "Visa process notes remain high-level ranges only.",
      "Photograph motifs favour campuses and libraries from stock sources.",
      "Nepal desks can syndicate adapted explainers for families at home.",
      "A glossary of common enrolment terms closes the piece.",
    ],
    focusNp: [
      "अभिमुखीकरणमा आवास ठगी सचेतना र क्याम्पस कल्याण सेवा समेटिएको छ।",
      "विद्यार्थी युनियनले निजी केस नखुलाई साथी मेन्टरिङ छलफल गर्छन्।",
      "भिसा प्रक्रिया नोट उच्च स्तरका दायरा मात्र हुन्।",
      "तस्बिर क्याम्पस र पुस्तकालय स्टक स्रोतबाट।",
      "नेपाल डेस्कले घरका परिवारका लागि अनुकूलित व्याख्या पठाउन सक्छ।",
      "सामान्य भर्ना शब्दावली शब्दकोशसहित लेख टुंगिन्छ।",
    ],
  },
  {
    categorySlug: "economy-business",
    auRegion: "QLD",
    title: "Brisbane small-business networking nights for migrant founders",
    titleNp: "ब्रिस्बेनमा आप्रवासी संस्थापकका लागि साना व्यवसाय नेटवर्किङ रात्रि",
    imageQuery: "brisbane australia business",
    tagSlugs: ["australia", "business-tag", "nepali-community"],
    placeEn: "Brisbane",
    placeNp: "ब्रिस्बेन",
    focusEn: [
      "Pitch practice rounds and mentor office hours are described for demo UX.",
      "No funding awards are presented as confirmed.",
      "Chambers of commerce appear as generic facilitators.",
      "Topics include invoicing basics and local market research habits.",
      "Cross-links to business category articles improve related rails.",
      "Readers are reminded this is development seed content.",
    ],
    focusNp: [
      "पिच अभ्यास र मेन्टर कार्यालय समय डेमो यूएक्सका लागि वर्णन छ।",
      "कुनै वित्त पुरस्कार पुष्टि भनिएको छैन।",
      "वाणिज्य कक्ष सामान्य सहजकर्ताका रूपमा छन्।",
      "इनभ्वाइसिङ आधार र स्थानीय बजार अनुसन्धान बानी समेटिएको छ।",
      "व्यापार श्रेणीसँग लिंकले सम्बन्धित रेल सुधार्छ।",
      "यो विकास सिड सामग्री हो भनी पाठकलाई स्मरण।",
    ],
  },
  {
    categorySlug: "health-lifestyle",
    auRegion: "SA",
    title: "Adelaide community clinics publish multilingual appointment guides",
    titleNp: "एडिलेड सामुदायिक क्लिनिकले बहुभाषी अपोइन्टमेन्ट गाइड प्रकाशित",
    imageQuery: "adelaide australia healthcare",
    tagSlugs: ["australia", "public-health", "nepali-community"],
    placeEn: "Adelaide",
    placeNp: "एडिलेड",
    focusEn: [
      "Guides cover interpreter requests and after-hours options in plain language.",
      "No clinical advice or drug claims are included.",
      "Stock imagery depicts generic clinic exteriors.",
      "Nepali and English strings both carry full paragraphs for layout tests.",
      "Service journalism framing keeps dignity first.",
      "Editors should verify live clinic details before any non-demo reuse.",
    ],
    focusNp: [
      "गाइडमा दोभाषे अनुरोध र अफ-आवर विकल्प सरल भाषामा छन्।",
      "क्लिनिकल सल्लाह वा औषधि दाबी छैन।",
      "स्टक तस्बिर सामान्य क्लिनिक बाहिरी दृश्य देखाउँछ।",
      "नेपाली र अङ्ग्रेजी दुवैमा पूर्ण अनुच्छेद लेआउट परीक्षणका लागि छन्।",
      "सेवा पत्रकारितामा मर्यादा प्राथमिक छ।",
      "डेमो बाहेक प्रयोगअघि लाइभ क्लिनिक विवरण पुष्टि गर्नुहोस्।",
    ],
  },
  {
    categorySlug: "technology-science",
    auRegion: "WA",
    title: "Perth tech meetups share beginner cloud lab outlines",
    titleNp: "पर्थ टेक मीटअपमा शुरुआती क्लाउड ल्याब रूपरेखा",
    imageQuery: "perth australia technology",
    tagSlugs: ["australia", "technology-tag", "software"],
    placeEn: "Perth",
    placeNp: "पर्थ",
    focusEn: [
      "Sessions emphasise free-tier sandboxes and cost-control habits.",
      "Speakers remain unnamed composites for demo safety.",
      "Security basics include MFA and secret scanning reminders.",
      "Nepali students in STEM clubs are referenced generally.",
      "Related modules can pull other technology explainers.",
      "Closing notes list open learning repositories.",
    ],
    focusNp: [
      "सत्रले निःशुल्क टियर स्यान्डबक्स र लागत नियन्त्रण बानीमा जोड दिन्छ।",
      "वक्ता डेमो सुरक्षाका लागि नामबिना मिश्रित पात्र हुन्।",
      "सुरक्षा आधारमा एमएफए र सीक्रेट स्क्यान स्मरण छ।",
      "एसटीईएम क्लबका नेपाली विद्यार्थी सामान्य सन्दर्भमा छन्।",
      "सम्बन्धित मोड्युलले अन्य प्रविधि व्याख्या तान्न सक्छ।",
      "अन्त्यमा खुला सिकाइ भण्डार सूची छ।",
    ],
  },
  {
    categorySlug: "sports",
    auRegion: "TAS",
    title: "Hobart weekend leagues welcome multicultural football sides",
    titleNp: "होबार्ट सप्ताहन्त लिगमा बहुसांस्कृतिक फुटबल टोली स्वागत",
    imageQuery: "hobart australia sports football",
    tagSlugs: ["australia", "football", "nepali-community"],
    placeEn: "Hobart",
    placeNp: "होबार्ट",
    focusEn: [
      "Fixture apps, ground bookings and fair-play codes are summarised.",
      "No match results are fabricated.",
      "Community photos use stock stadium scenes.",
      "Inclusion notes cover kit libraries and junior pathways.",
      "Sports desks can test AU region filters with this item.",
      "A volunteer referee FAQ wraps the feature.",
    ],
    focusNp: [
      "फिक्स्चर एप, मैदान बुकिङ र निष्पक्ष खेल संहिता सारांश छ।",
      "कुनै खेल परिणाम बनाइएको छैन।",
      "स्टक स्टेडियम दृश्य प्रयोग।",
      "किट लाइब्रेरी र जुनियर मार्ग समावेशी नोटमा छन्।",
      "खेलकुद डेस्कले एयू क्षेत्र फिल्टर परीक्षण गर्न सक्छ।",
      "स्वयंसेवक रेफ्री सामान्य प्रश्नसहित फिचर सकिन्छ।",
    ],
  },
  {
    categorySlug: "politics",
    auRegion: "ACT",
    title: "Canberra civic briefings explain petition pathways for residents",
    titleNp: "क्यानबरा नागरिक ब्रिफिङमा बासिन्दाका लागि निवेदन मार्ग व्याख्या",
    imageQuery: "canberra australia parliament",
    tagSlugs: ["australia", "government", "explainer"],
    placeEn: "Canberra",
    placeNp: "क्यानबरा",
    focusEn: [
      "Process journalism outlines submission windows without inventing policy outcomes.",
      "Community legal centres appear as referral points only.",
      "Nepal–Australia relations are mentioned as cultural and education ties, not claims.",
      "Bilingual bodies support English edition testing on en.* hosts.",
      "Photograph cues favour parliament exteriors from free stock.",
      "Transparency glossaries help new reporters.",
    ],
    focusNp: [
      "प्रक्रिया पत्रकारिताले नीति परिणाम नबनाई निवेदन समयरेखा बताउँछ।",
      "सामुदायिक कानुनी केन्द्र सिफारिस बिन्दु मात्र हुन्।",
      "नेपाल–अष्ट्रेलिया सम्बन्ध सांस्कृतिक र शिक्षा सम्बन्धका रूपमा मात्र।",
      "द्विभाषी बडीले अङ्ग्रेजी संस्करण परीक्षण सहयोग गर्छ।",
      "तस्बिरका लागि निःशुल्क स्टक संसद बाहिरी दृश्य।",
      "पारदर्शिता शब्दकोश नयाँ रिपोर्टरलाई सहयोगी।",
    ],
  },
  {
    categorySlug: "society",
    auRegion: "NT",
    title: "Darwin multicultural festivals document food stall safety drills",
    titleNp: "डार्विन बहुसांस्कृतिक महोत्सवमा खाना स्टल सुरक्षा अभ्यास",
    imageQuery: "darwin australia festival community",
    tagSlugs: ["australia", "nepali-community", "society-tag"],
    placeEn: "Darwin",
    placeNp: "डार्विन",
    focusEn: [
      "Organisers rehearse hygiene, queues and waste sorting with volunteers.",
      "No vendor fines or inspections are invented.",
      "Nepali stalls are referenced as part of a wider diaspora mosaic.",
      "Heat safety reminders suit northern climate context.",
      "Society pages gain AU-tagged demos for grids.",
      "A volunteer shift template concludes the article.",
    ],
    focusNp: [
      "आयोजकले स्वयंसेवकसँग स्वच्छता, लाइन र फोहोर छुट्याउने अभ्यास गर्छन्।",
      "कुनै विक्रेता जरिवाना बनाइएको छैन।",
      "नेपाली स्टल फराकिलो डायस्पोरा चित्रको अंशका रूपमा।",
      "उत्तरी जलवायु सन्दर्भमा ताप सुरक्षा स्मरण।",
      "समाज पृष्ठमा एयू ट्याग डेमो ग्रिडका लागि उपयोगी।",
      "स्वयंसेवक सिफ्ट टेम्प्लेटसहित लेख सकिन्छ।",
    ],
  },
  {
    categorySlug: "world",
    auRegion: "NSW",
    title: "Nepal–Australia education corridor explainers for families",
    titleNp: "परिवारका लागि नेपाल–अष्ट्रेलिया शिक्षा करिडोर व्याख्या",
    imageQuery: "australia education students international",
    tagSlugs: ["australia", "immigration", "students", "international-tag"],
    placeEn: "Kathmandu / Sydney",
    placeNp: "काठमाडौँ / सिड्नी",
    focusEn: [
      "Families receive high-level questions to ask agents and universities.",
      "No visa outcomes are promised.",
      "Cost-of-living notes stay illustrative.",
      "Both language editions carry substantial paragraphs for SEO tests.",
      "Related tags improve search facets.",
      "Disclaimer boxes restate the demo nature of the dataset.",
    ],
    focusNp: [
      "परिवारले एजेन्ट र विश्वविद्यालयलाई सोध्ने उच्च स्तरीय प्रश्न पाउँछन्।",
      "भिसा परिणामको वाचा छैन।",
      "जीवन यापन लागत नोट उदाहरण मात्र।",
      "दुवै भाषा संस्करणमा एसईओ परीक्षणका लागि लामो अनुच्छेद।",
      "सम्बन्धित ट्यागले खोज पक्ष सुधार्छ।",
      "अस्वीकरण बाक्सले डेमो प्रकृति दोहोर्‍याउँछ।",
    ],
  },
  {
    categorySlug: "economy-business",
    auRegion: "VIC",
    title: "Melbourne logistics workshops for import-export beginners",
    titleNp: "मेलबर्नमा आयात–निर्यात शुरुआतीका लागि लजिस्टिक्स कार्यशाला",
    imageQuery: "melbourne australia business port",
    tagSlugs: ["australia", "business-tag", "markets"],
    placeEn: "Melbourne",
    placeNp: "मेलबर्न",
    focusEn: [
      "Incoterms overviews and packaging checklists are educational only.",
      "Ports and freight forwarders are discussed categorically.",
      "Nepali traders appear as composite learner personas.",
      "No customs rulings are fabricated.",
      "Business category grids receive AU regional diversity.",
      "Further reading lists public trade portals.",
    ],
    focusNp: [
      "इन्कोटर्म्स र प्याकेजिङ चेकलिस्ट शैक्षिक मात्र हुन्।",
      "बन्दरगाह र फ्रेट फर्वार्डर वर्गका रूपमा छलफल।",
      "नेपाली व्यापारी मिश्रित सिकारु व्यक्तित्वका रूपमा।",
      "भन्सार निर्णय बनाइएको छैन।",
      "व्यापार श्रेणी ग्रिडमा एयू क्षेत्रीय विविधता।",
      "थप पढाइमा सार्वजनिक व्यापार पोर्टल सूची।",
    ],
  },
  {
    categorySlug: "tourism-agriculture",
    auRegion: "QLD",
    title: "Gold Coast visitor centres trial Nepali phrase cards",
    titleNp: "गोल्ड कोस्ट पर्यटक केन्द्रमा नेपाली वाक्यांश कार्ड परीक्षण",
    imageQuery: "gold coast australia tourism",
    tagSlugs: ["australia", "tourism", "nepali-community"],
    placeEn: "Gold Coast",
    placeNp: "गोल्ड कोस्ट",
    focusEn: [
      "Phrase cards help hospitality staff greet diaspora and visiting families.",
      "No tourism board statistics are invented.",
      "Beach safety reminders remain evergreen.",
      "Images use coastal landscape stock suitable for 16:9.",
      "Tourism filters and AU regions both populate for QA.",
      "Volunteer translators are thanked generically.",
    ],
    focusNp: [
      "वाक्यांश कार्डले आतिथ्य स्टाफलाई डायस्पोरा र भ्रमण परिवार स्वागतमा सहयोग गर्छ।",
      "पर्यटन बोर्ड तथ्यांक बनाइएको छैन।",
      "समुद्र सुरक्षा स्मरण सधैं उपयोगी।",
      "१६:९ का लागि तटीय ल्यान्डस्केप स्टक।",
      "पर्यटन फिल्टर र एयू क्षेत्र दुवै क्यूएका लागि भरिन्छन्।",
      "स्वयंसेवक अनुवादकलाई सामान्य धन्यवाद।",
    ],
  },
  {
    categorySlug: "health-lifestyle",
    auRegion: "WA",
    title: "Perth weekend markets spotlight Himalayan food stalls",
    titleNp: "पर्थ सप्ताहन्त बजारमा हिमाली खाना स्टल स्पॉटलाइट",
    imageQuery: "perth australia market food",
    tagSlugs: ["australia", "lifestyle-tag", "nepali-community"],
    placeEn: "Perth",
    placeNp: "पर्थ",
    focusEn: [
      "Food hygiene and allergen signage tips keep the piece service-oriented.",
      "Vendor stories are composite.",
      "No health inspections are claimed.",
      "Lifestyle cards benefit from warm market photography.",
      "Tags connect diaspora and food culture facets.",
      "A recipe-free cultural notes box closes the article.",
    ],
    focusNp: [
      "खाना स्वच्छता र एलर्जी संकेत सुझाव सेवामुखी छन्।",
      "विक्रेता कथा मिश्रित हुन्।",
      "स्वास्थ्य निरीक्षण दाबी छैन।",
      "जीवनशैली कार्डलाई बजार फोटोग्राफी उपयोगी।",
      "ट्यागले डायस्पोरा र खाना संस्कृति जोड्छ।",
      "रेसिपीबिना सांस्कृतिक नोट बाक्ससहित सकिन्छ।",
    ],
  },
];

export function allCategoryPacks(): TopicPack[] {
  return [...CORE_PACKS, ...EXTRA];
}
