import type { TagSeedDef } from "./types";

export const TAG_DEFS: TagSeedDef[] = [
  { name: "Nepal Politics", nameNp: "नेपाली राजनीति", slug: "nepal-politics" },
  { name: "Government", nameNp: "सरकार", slug: "government" },
  { name: "Election", nameNp: "निर्वाचन", slug: "election" },
  { name: "Parliament", nameNp: "संसद", slug: "parliament" },
  { name: "Business", nameNp: "व्यापार", slug: "business-tag" },
  { name: "Banking", nameNp: "बैंकिङ", slug: "banking" },
  { name: "Markets", nameNp: "बजार", slug: "markets" },
  { name: "AI", nameNp: "एआई", slug: "ai" },
  { name: "Technology", nameNp: "प्रविधि", slug: "technology-tag" },
  { name: "Digital Nepal", nameNp: "डिजिटल नेपाल", slug: "digital-nepal" },
  { name: "Software", nameNp: "सफ्टवेयर", slug: "software" },
  { name: "Cricket", nameNp: "क्रिकेट", slug: "cricket" },
  { name: "Football", nameNp: "फुटबल", slug: "football" },
  { name: "Film", nameNp: "चलचित्र", slug: "film" },
  { name: "Music", nameNp: "संगीत", slug: "music" },
  { name: "Public Health", nameNp: "जनस्वास्थ्य", slug: "public-health" },
  { name: "Hospitals", nameNp: "अस्पताल", slug: "hospitals" },
  { name: "Education", nameNp: "शिक्षा", slug: "education-tag" },
  { name: "Students", nameNp: "विद्यार्थी", slug: "students" },
  { name: "Society", nameNp: "समाज", slug: "society-tag" },
  { name: "Lifestyle", nameNp: "जीवनशैली", slug: "lifestyle-tag" },
  { name: "Tourism", nameNp: "पर्यटन", slug: "tourism" },
  { name: "Trekking", nameNp: "ट्रेकिङ", slug: "trekking" },
  { name: "Agriculture", nameNp: "कृषि", slug: "agriculture-tag" },
  { name: "Farmers", nameNp: "किसान", slug: "farmers" },
  { name: "Science", nameNp: "विज्ञान", slug: "science-tag" },
  { name: "Research", nameNp: "अनुसन्धान", slug: "research" },
  { name: "Climate", nameNp: "जलवायु", slug: "climate" },
  { name: "Environment", nameNp: "वातावरण", slug: "environment-tag" },
  { name: "National", nameNp: "राष्ट्रिय", slug: "national-tag" },
  { name: "International", nameNp: "अन्तर्राष्ट्रिय", slug: "international-tag" },
  { name: "Australia", nameNp: "अष्ट्रेलिया", slug: "australia" },
  { name: "Sydney", nameNp: "सिड्नी", slug: "sydney" },
  { name: "Melbourne", nameNp: "मेलबर्न", slug: "melbourne" },
  { name: "Nepali Community", nameNp: "नेपाली समुदाय", slug: "nepali-community" },
  { name: "Immigration", nameNp: "आप्रवासन", slug: "immigration" },
  { name: "Hydropower", nameNp: "जलविद्युत्", slug: "hydropower" },
  { name: "Feature", nameNp: "फिचर", slug: "feature" },
  { name: "Explainer", nameNp: "व्याख्यात्मक", slug: "explainer" },
];
